# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :bash => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  },
#  :mysql => {
#        :box_name => "centos/7",
#        :ip_addr => '192.168.11.102'
#  },
#  :nginx => {
#        :box_name => "centos/7",
#        :ip_addr => '192.168.11.103'
#  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end

          box.vm.provision "shell", inline: <<-SHELL
#            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
#          yum install vim -y
         #OUEST1
          cp /vagrant/1_watchlog /etc/sysconfig/watchlog
          cp /vagrant/1_watchlog.log /var/log/watchlog.log
          cp /vagrant/1_watchlog.sh /opt/watchlog.sh
          cp /vagrant/1_watchlog.service /lib/systemd/system/watchlog.service
          cp /vagrant/1_watchlog.timer /lib/systemd/system/watchlog.timer
          chmod +x /opt/watchlog.sh
          ln -s /lib/systemd/system/watchlog.service /etc/systemd/system/multi-user.target.wants/
          ln -s /lib/systemd/system/watchlog.timer /etc/systemd/system/multi-user.target.wants/
         #QUEST2
          yum install httpd -y
          cp /vagrant/2_httpd@,service /lib/systemd/system/httpd@.service 
          cp /vagrant/2_httpd-first /etc/sysconfig/httpd-first
          cp /vagrant/2_httpd-second /etc/sysconfig/httpd-second
          cp /vagrant/2_first.conf /etc/httpd/conf/first.conf
          cp /vagrant/2_second.conf /etc/httpd/conf/second.conf
          ln -s /lib/systemd/system/httpd@first.service /etc/systemd/system/multi-user.target.wants/
          ln -s /lib/systemd/system/httpd@second.service /etc/systemd/system/multi-user.target.wants/
         #QUEST3
          yum install wget -y
          wget https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.7.1-x64.bin
          chmod 755 jira*     
          ./jira*
          cp /vagrant/3_jira.service /lib/systemd/system/jira.service
          ln -s /lib/systemd/system/jira.service /etc/systemd/system/multi-user.target.wants/
          systemctl set-property jira.service CPUQuota=40%          
          SHELL

      end
  end
end
